spring.application.name=VaultDesk-server
spring.datasource.url=jdbc:sqlite:vaultdesk.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.sql.init.mode=always
server.port=2008